/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2025-02-09 07:03:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.eshoping.DAO.CartDAOimpl;
import com.eshoping.DAO.CartDAO;
import com.eshoping.modeal.Product_Details;
import java.util.List;
import com.eshoping.DAO.ProductsDAO;
import com.eshoping.DAO.ProductDAOimpl;
import com.eshoping.modeal.Customer_Details;

public final class AllproductsCustomer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.eshoping.DAO.ProductsDAO");
    _jspx_imports_classes.add("com.eshoping.DAO.CartDAOimpl");
    _jspx_imports_classes.add("com.eshoping.modeal.Product_Details");
    _jspx_imports_classes.add("com.eshoping.modeal.Customer_Details");
    _jspx_imports_classes.add("com.eshoping.DAO.ProductDAOimpl");
    _jspx_imports_classes.add("com.eshoping.DAO.CartDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>All Product Details</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./FooterStyle.css?v=1.1\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Helvetica Neue', Arial, sans-serif;\r\n");
      out.write("	background: black;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	color: #FFD700; /* Gold text */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	font-size: 36px;\r\n");
      out.write("	color: #FFD700; /* Gold */\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("h1:hover{\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("	color: orange;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#OrderDetails {\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	width: 160px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 20px;\r\n");
      out.write("	top: 20px;\r\n");
      out.write("	border-radius: 30px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	border: 3px solid #FFD700; /* Gold border */\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	background-color: #121212; /* Black */\r\n");
      out.write("	color: #FFD700; /* Gold */\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#OrderDetails:hover {\r\n");
      out.write("	background: linear-gradient(45deg, #FFD700, #FFD700);\r\n");
      out.write("	color: black; /* Black text */\r\n");
      out.write("	border: 3px solid orange;\r\n");
      out.write("	transform: scale(1.06);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 22px;\r\n");
      out.write("	color: #FFD700; /* Gold */\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-button {\r\n");
      out.write("	background-color: #FFD700; /* Gold */\r\n");
      out.write("	color: black; /* Black text */\r\n");
      out.write("	border: 3px solid orange;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	padding: 12px 20px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	border-radius: 30px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	transition: background-color 0.3s ease, transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-button sup {\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	color: #FFD700; /* Gold */\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	padding: 5px 10px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: -10px;\r\n");
      out.write("	right: -10px;\r\n");
      out.write("	border: 3px solid orange;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-button:hover {\r\n");
      out.write("	background: linear-gradient(45deg, #FFD700, #FFD700);\r\n");
      out.write("	color: #121212; /* Black */\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Product grid styling */\r\n");
      out.write(".product-grid {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	gap: 20px;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card-wrapper {\r\n");
      out.write("	background-color: #1C1C1C; /* Slight light color for card */\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 0px 4px 12px rgba(255, 215, 0, 0.2); /* Gold shadow */\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("	border: 2px solid #FFD700; /* Gold border */\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 520px;\r\n");
      out.write("	/* Flexbox for card content */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	opacity: 0; /* Initially hidden */\r\n");
      out.write("	transform: translateY(20px); /* Start with slight translation */\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card-wrapper:hover {\r\n");
      out.write("	box-shadow: 0 6px 16px rgba(255, 215, 0, 0.4);\r\n");
      out.write("	transform: scale(1.03);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card-wrapper.visible {\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("	transform: translateY(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Product image */\r\n");
      out.write(".product-card img {\r\n");
      out.write("	width: 66%;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("	object-fit: contain;\r\n");
      out.write("	background: linear-gradient(45deg, rgba(255, 215, 0, 0.1), rgba(255, 140, 0, 0.2)); /* Glowing background */\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("	border: 3px solid orange;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card img:hover {\r\n");
      out.write("	background: linear-gradient(45deg, #FFD700, #FFD700);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card h3 {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	color: #E5C100; /* Lighter Gold for text */\r\n");
      out.write("	margin-top: 6px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card p {\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: #BDB76B; /* Light gold */\r\n");
      out.write("	margin-bottom: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card .actual-price {\r\n");
      out.write("	margin-top: 3%;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	color: green;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card .discounted-price {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	color: #FF4500; /* Red for the strike-through price */\r\n");
      out.write("	text-decoration: line-through;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-buttons {\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	gap: 10px;\r\n");
      out.write("	justify-content: flex-end;\r\n");
      out.write("	flex-grow: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-buttons input[type=\"submit\"] {\r\n");
      out.write("	background-color: #FFD700; /* Gold */\r\n");
      out.write("	color: black; /* Black text */\r\n");
      out.write("	padding: 6px 10px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	border: 3px solid orange;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 30px;\r\n");
      out.write("	transition: background-color 0.3s ease, transform 0.3s ease;\r\n");
      out.write("	width: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-buttons input[type=\"submit\"]:hover {\r\n");
      out.write("	background: linear-gradient(45deg, #FFD700, #FFD700);\r\n");
      out.write("	color: black; /* Black text */\r\n");
      out.write("	transform: scale(1.06);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#searchContainer {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	gap: 10px;\r\n");
      out.write("	margin: 30px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#searchBar {\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	border: 2px solid #FFD700; /* Gold border */\r\n");
      out.write("	border-radius: 30px;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	background-color: black; /* Black background */\r\n");
      out.write("	color: #FFD700; /* Gold text */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#searchBar:focus {\r\n");
      out.write("	border-color: orange; /* Gold */\r\n");
      out.write("	box-shadow: 0 0 5px rgba(255, 215, 0, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#buttonSub {\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	background-color: #FFD700; /* Gold */\r\n");
      out.write("	color: black; /* Black text */\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 30px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background-color 0.3s ease, transform 0.3s ease;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	border: 3px solid orange;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#buttonSub:hover {\r\n");
      out.write("	background: linear-gradient(45deg, #FFD700, #FFD700);\r\n");
      out.write("	color: black; /* Black text */\r\n");
      out.write("	border: 3px solid orange;\r\n");
      out.write("	transform:scale(1.04);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media only screen and (max-width: 768px) {\r\n");
      out.write("	.product-grid {\r\n");
      out.write("		grid-template-columns: repeat(2, 1fr);\r\n");
      out.write("	}\r\n");
      out.write("	.product-card-wrapper {\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	#searchBar {\r\n");
      out.write("		width: 80%;\r\n");
      out.write("	}\r\n");
      out.write("	#buttonSub {\r\n");
      out.write("		width: 80%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#NotFound p {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: #FFD700; /* Gold */\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:disabled {\r\n");
      out.write("  background-color: #555555 !important;\r\n");
      out.write("  color: #777777 !important;\r\n");
      out.write("  border: 3px solid #777777 !important;\r\n");
      out.write("  cursor: not-allowed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:disabled:hover {\r\n");
      out.write("  background-color: #555555 !important;\r\n");
      out.write("  color: #777777 !important;\r\n");
      out.write("  transform: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("    const productCards = document.querySelectorAll(\".product-card-wrapper\");\r\n");
      out.write("    productCards.forEach((card, index) => {\r\n");
      out.write("        setTimeout(() => {\r\n");
      out.write("            card.classList.add(\"visible\"); // Make the card visible with animation\r\n");
      out.write("        }, 200 * index); // 200ms delay for each card\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

Customer_Details customer = (Customer_Details) session.getAttribute("loginincludecustomerdetail");

ProductsDAO productsDAO = new ProductDAOimpl();
List<Product_Details> allProducts = null;

CartDAO cartDAO = new CartDAOimpl();
int cartCount = cartDAO.getCustomerCartCount(customer.getId());
String search = request.getParameter("value");
if (search == null || search.equalsIgnoreCase("all")) {
    allProducts = productsDAO.getAllProducts();
} else {
    allProducts = productsDAO.Applyfilter(search);
}

      out.write("\r\n");
      out.write("	<h1>All Product Details</h1>\r\n");
      out.write("	<button id=\"OrderDetails\"\r\n");
      out.write("		onclick=\"window.location.href='CustomerOrders.jsp'\">My Orders</button>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		");
      out.print( customer.getName() );
      out.write("<br>\r\n");
      out.write("		<button onclick=\"window.location.href='CurrentCart.jsp'\"\r\n");
      out.write("			class=\"cart-button\">\r\n");
      out.write("			My Cart <sup>");
      out.print( cartCount );
      out.write("</sup>\r\n");
      out.write("		</button>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"AllproductsCustomer.jsp\" method=\"get\">\r\n");
      out.write("		<div id=\"searchContainer\">\r\n");
      out.write("			<input id=\"searchBar\" type=\"search\"\r\n");
      out.write("				placeholder=\"Search by Category, Brand, or Name\" name=\"value\"\r\n");
      out.write("				autocomplete=\"off\" required> <input id=\"buttonSub\"\r\n");
      out.write("				type=\"submit\" value=\"Search\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"product-grid\">\r\n");
      out.write("\r\n");
      out.write("		");
 
    if (allProducts != null && !allProducts.isEmpty()) {
        for (Product_Details product : allProducts) {
    
      out.write("\r\n");
      out.write("		<a href=\"ProductSelect.jsp?productId=");
      out.print( product.getId() );
      out.write("&CustomerId=");
      out.print( customer.getId() );
      out.write("\">\r\n");
      out.write("			<div class=\"product-card-wrapper\">\r\n");
      out.write("				<div class=\"product-card\">\r\n");
      out.write("\r\n");
      out.write("					<img alt=\"Product Image\" src=\"images/");
      out.print( product.getImageurl() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("					<h3>");
      out.print( product.getName() );
      out.write("</h3>\r\n");
      out.write("					<p><strong>Category:</strong> ");
      out.print( product.getCategory() );
      out.write("</p>\r\n");
      out.write("					<p><strong>Brand:</strong> ");
      out.print( product.getBrand() );
      out.write("</p>\r\n");
      out.write("					<p><strong>Discount:</strong> ");
      out.print( product.getDiscount() );
      out.write("%</p>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"actual-price\">\r\n");
      out.write("						&#8377;");
      out.print( (int) Math.floor(product.getPrise() - (product.getPrise() * product.getDiscount() / 100)) );
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"discounted-price\">\r\n");
      out.write("						<strong>&#8377;");
      out.print( product.getPrise() );
      out.write("</strong>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-buttons\">\r\n");
      out.write("						<form action=\"AddtoCart\">\r\n");
      out.write("							<input hidden=\"true\" value=");
      out.print(request.getRequestURL());
      out.write(" name=\"preUrl\">\r\n");
      out.write("							<input value=\"");
      out.print( product.getId() );
      out.write("\" hidden=\"true\"\r\n");
      out.write("								name=\"productId\"> <input value=\"");
      out.print( customer.getId() );
      out.write("\"\r\n");
      out.write("								hidden=\"true\" name=\"CustomerId\"> \r\n");
      out.write("							<input type=\"submit\" value=\"Add To Cart\">\r\n");
      out.write("						</form>\r\n");
      out.write("						<form action=\"CheckOut.jsp\">\r\n");
      out.write("							<input value=\"");
      out.print( product.getId() );
      out.write("\" hidden=\"true\"\r\n");
      out.write("								name=\"productId\"> <input value=\"");
      out.print( customer.getId() );
      out.write("\"\r\n");
      out.write("								hidden=\"true\" name=\"CustomerId\"> \r\n");
      out.write("							<input type=\"submit\" value=\"Buy\">\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</a>\r\n");
      out.write("		");
 
        }
    } else {	
    
      out.write("\r\n");
      out.write("		<div id=\"NotFound\">\r\n");
      out.write("			<p>No Products Available At This Time</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
 
    }
    
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./FooterStyle.css?v=1.1\">\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footer-container\">\r\n");
      out.write("        <!-- About Section (Vertical at the top) -->\r\n");
      out.write("        <div class=\"footer-about\">\r\n");
      out.write("            <h4>About Your E-Shop</h4>\r\n");
      out.write("            <p>\r\n");
      out.write("                Your E-Shop is your go-to destination for quality products and unbeatable deals.\r\n");
      out.write("                Explore a wide range of categories, enjoy a seamless shopping experience, and find\r\n");
      out.write("                everything you need in one place.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Remaining Sections (Horizontal below the About section) -->\r\n");
      out.write("        <div class=\"footer-remaining\">\r\n");
      out.write("            <!-- Quick Links Section -->\r\n");
      out.write("            <div class=\"footer-links\">\r\n");
      out.write("                <h4>Quick Links</h4>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"HomePage.jsp\">Home</a></li>\r\n");
      out.write("                    <li><a href=\"ProductsPage.jsp\">Shop Products</a></li>\r\n");
      out.write("                    <li><a href=\"ContactUsPage.jsp\">Contact Us</a></li>\r\n");
      out.write("                    <li><a href=\"FAQPage.jsp\">FAQs</a></li>\r\n");
      out.write("                    <li><a href=\"TermsAndConditions.jsp\">Terms & Conditions</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Contact Section -->\r\n");
      out.write("            <div class=\"footer-contact\">\r\n");
      out.write("                <h4>Contact Us</h4>\r\n");
      out.write("                <p>Email: <a href=\"mailto:support@youreshop.com\">support@youreshop.com</a></p>\r\n");
      out.write("                <p>Phone: +1 234 567 890</p>\r\n");
      out.write("                <p>Address: 123 E-Shop Lane, Shopville</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Social Media Links -->\r\n");
      out.write("            <div class=\"footer-social\">\r\n");
      out.write("                <h4>Follow Us</h4>\r\n");
      out.write("                <div class=\"social-icons\">\r\n");
      out.write("                    <a href=\"#\" aria-label=\"Facebook\"><i class=\"fab fa-facebook-f\"></i><label id=\"fb\">Facebook</label></a><br>\r\n");
      out.write("                    <a href=\"#\" aria-label=\"Twitter\"><i class=\"fab fa-twitter\"></i><label id=\"twit\">Twitter</label></a><br>\r\n");
      out.write("                    <a href=\"#\" aria-label=\"Instagram\"><i class=\"fab fa-instagram\"></i><label id=\"insta\">Instagram</label></a><br>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"button\">\r\n");
      out.write("    	<button id=\"truble\" onclick=\"window.location.href=`ContactUsPage.jsp?CustomerId=");
      out.print( customer.getId() );
      out.write("`;\">Contact..?</button>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
