/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2025-02-09 07:04:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.eshoping.DAO.ProductDAOimpl;
import com.eshoping.DAO.ProductsDAO;
import com.eshoping.DAO.CartDAOimpl;
import com.eshoping.DAO.CartDAO;
import com.eshoping.modeal.Product_Details;
import com.eshoping.modeal.Customer_Details;
import java.util.List;

public final class CheckOut_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.eshoping.DAO.ProductsDAO");
    _jspx_imports_classes.add("com.eshoping.DAO.CartDAOimpl");
    _jspx_imports_classes.add("com.eshoping.modeal.Product_Details");
    _jspx_imports_classes.add("com.eshoping.modeal.Customer_Details");
    _jspx_imports_classes.add("com.eshoping.DAO.ProductDAOimpl");
    _jspx_imports_classes.add("com.eshoping.DAO.CartDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Customer_Details customer = (Customer_Details) session.getAttribute("loginincludecustomerdetail");
    ProductsDAO productsDAO = new ProductDAOimpl();
    List<Product_Details> allProducts = productsDAO.getAllProducts();
    int proid = Integer.parseInt(request.getParameter("productId"));
    
    Product_Details currentProduct = null;
    for (Product_Details product : allProducts) {
        if (proid == product.getId()) {
            currentProduct = product;
            break;
        }
    }
    session.setAttribute("CurrentProduct", currentProduct);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Product Details</title>\r\n");
      out.write("    <!-- Compact CSS styling -->\r\n");
      out.write("    <style>\r\n");
      out.write("        /* CSS styles (Black and Golden theme) */\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("            background-color: #212121; /* Black background */\r\n");
      out.write("            color: #f1c40f; /* Golden text color */\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: 1fr 2fr;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-image {\r\n");
      out.write("            max-width: 100%;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        img{\r\n");
      out.write("        	width:300px;\r\n");
      out.write("        	height:400px;\r\n");
      out.write("        	border: 5px solid #f1c40f; /* Golden border */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-details {\r\n");
      out.write("            background-color: #333333; /* Dark background for product details */\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            border:3px solid #f1c40f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #f1c40f; /* Golden color for headers */\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1:hover {\r\n");
      out.write("            color: orange;\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-details table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-details th, .product-details td {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-details th {\r\n");
      out.write("            background-color: #444444; /* Dark background for headers */\r\n");
      out.write("            color: #f1c40f; /* Golden color */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"], input[type=\"number\"], input[type=\"radio\"], input[type=\"submit\"] {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border: none; /* Removed border */\r\n");
      out.write("            background-color: #444444; /* Dark input background */\r\n");
      out.write("            color: #f1c40f; /* Golden text */\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border:3px solid orange;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        #quantityInput{\r\n");
      out.write("        	color: black;\r\n");
      out.write("        	outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .calc-output {\r\n");
      out.write("            width: 96%;\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("            background-color: #333333;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            display: none;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .calc-output h2 {\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            color: #f1c40f; /* Golden color */\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .calc-output h2:hover \r\n");
      out.write("        {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #f1c40f; /* Golden color for headers */\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("            color: orange;\r\n");
      out.write("        }\r\n");
      out.write("        .calc-output input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            background-color: #444444; /* Dark background */\r\n");
      out.write("            color: #f1c40f; /* Golden text */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .calc-output input:disabled {\r\n");
      out.write("            background-color: #555555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .calc-output input.valid {\r\n");
      out.write("            background-color: #e0f7e0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .calc-output input.invalid {\r\n");
      out.write("            background-color: #ffcccc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #paymentMethods {\r\n");
      out.write("            display: none;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: #333333;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("            border: 2px solid #f1c40f; /* Golden border */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #paymentMethods label {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            color: #f1c40f; /* Golden color */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-options {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));\r\n");
      out.write("            gap: 30px;\r\n");
      out.write("            margin-top:10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-options input[type=\"radio\"] {\r\n");
      out.write("            display: none; /* Hide the default radio button */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-options label {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-content: center;\r\n");
      out.write("            justify-content: flex-start;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            background-color: #444444;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            color: #f1c40f;\r\n");
      out.write("            transition: background-color 0.3s ease, color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-options label::before {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            border: 2px solid #f1c40f; /* Golden border */\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            background-color: #333333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-options input[type=\"radio\"]:checked+label {\r\n");
      out.write("            background-color: #333333;\r\n");
      out.write("            border: 3px solid orange;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-options input[type=\"radio\"]:checked+label::before {\r\n");
      out.write("            background-color: orange;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-options label:hover {\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-options input[type=\"radio\"]:disabled+label {\r\n");
      out.write("            background-color: #555555;\r\n");
      out.write("            color: #888888;\r\n");
      out.write("            cursor: not-allowed;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-options input[type=\"radio\"]:disabled+label::before {\r\n");
      out.write("            border-color: #555555;\r\n");
      out.write("            background-color: #444444;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #paymentMethods .submit-button {\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            background-color: #f1c40f; /* Golden background */\r\n");
      out.write("            color: black;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #paymentMethods .submit-button:hover {\r\n");
      out.write("            background-color: #e0b90f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .confirm-button {\r\n");
      out.write("            background-color: #f1c40f; /* Golden color */\r\n");
      out.write("            color: black;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .confirm-button:hover {\r\n");
      out.write("            background-color: #e0b90f;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input.invalid {\r\n");
      out.write("            background-color: #ffcccc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input.valid {\r\n");
      out.write("            background-color: #e0f7e0;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function calculateSum() {\r\n");
      out.write("            let Qty = parseInt(document.getElementById('quantityInput').value);\r\n");
      out.write("            let stock = parseInt(document.getElementById('stockAvailable').value);\r\n");
      out.write("            let quantityInput = document.getElementById('quantityInput');\r\n");
      out.write("            \r\n");
      out.write("            if (Qty <= 0 || isNaN(Qty) || Qty > stock) {\r\n");
      out.write("                quantityInput.classList.remove('valid');\r\n");
      out.write("                quantityInput.classList.add('invalid');\r\n");
      out.write("                document.querySelector('.calc-output').style.display = 'none';\r\n");
      out.write("                document.getElementById('paymentMethods').style.display = 'none';\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            quantityInput.classList.remove('invalid');\r\n");
      out.write("            quantityInput.classList.add('valid');\r\n");
      out.write("\r\n");
      out.write("            let UnitCost = parseFloat(document.getElementById('productPrice').value);\r\n");
      out.write("            let Discount = parseFloat(document.getElementById('productDiscount').value);\r\n");
      out.write("            \r\n");
      out.write("            let TotalCost = UnitCost * Qty;\r\n");
      out.write("            let TotalAfterDiscount = TotalCost - (TotalCost * (Discount / 100));\r\n");
      out.write("            \r\n");
      out.write("            document.getElementById('purchaseQuantity').value = 'Purchase Quantity: ' + Qty;\r\n");
      out.write("            document.getElementById('unitCost').value = 'Unit Cost: ' + UnitCost.toFixed(2);\r\n");
      out.write("            document.getElementById('discount').value = 'Unit Discount: ' + Discount.toFixed(2);\r\n");
      out.write("            document.getElementById('totalCost').value = 'Total Cost: ' + TotalCost.toFixed(2);\r\n");
      out.write("            document.getElementById('discountDeduction').value = 'Total Discount: ' + (TotalCost * (Discount / 100)).toFixed(2);\r\n");
      out.write("            document.getElementById('totalDiscount').value = 'Payable Ammount: ' + TotalAfterDiscount.toFixed(2);\r\n");
      out.write("            document.getElementById('sendQuantity').value = Qty;\r\n");
      out.write("            document.getElementById('sendtotalCost').value = TotalAfterDiscount.toFixed(2);\r\n");
      out.write("            \r\n");
      out.write("            document.querySelector('.calc-output').style.display = 'block';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function showPaymentMethods() {\r\n");
      out.write("            let Qty = parseInt(document.getElementById('quantityInput').value);\r\n");
      out.write("            let stock = parseInt(document.getElementById('stockAvailable').value);\r\n");
      out.write("\r\n");
      out.write("            if (Qty > 0 && Qty <= stock) {\r\n");
      out.write("                document.getElementById('paymentMethods').style.display = 'block';\r\n");
      out.write("            } else {\r\n");
      out.write("                alert('Please enter a valid quantity between ' + 1 + ' and ' + stock + '.');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"product-image\">\r\n");
      out.write("            <img src=\"images/");
      out.print( currentProduct.getImageurl() );
      out.write("\"\r\n");
      out.write("                 alt=\"");
      out.print( currentProduct.getName() );
      out.write("\" class=\"product-image\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"product-details\">\r\n");
      out.write("            <h1>Product Details</h1>\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label for=\"productName\">Name</label></td>\r\n");
      out.write("                    <td><input type=\"text\" id=\"productName\" value=\"");
      out.print( currentProduct.getName() );
      out.write("\" disabled></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label for=\"productBrand\">Brand</label></td>\r\n");
      out.write("                    <td><input type=\"text\" id=\"productBrand\" value=\"");
      out.print( currentProduct.getBrand() );
      out.write("\" disabled></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label for=\"productPrice\">Price</label></td>\r\n");
      out.write("                    <td><input type=\"number\" id=\"productPrice\" value=\"");
      out.print( currentProduct.getPrise() );
      out.write("\" disabled></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label for=\"stockAvailable\">Stock Available</label></td>\r\n");
      out.write("                    <td><input type=\"number\" id=\"stockAvailable\" value=\"");
      out.print( currentProduct.getQuantity() );
      out.write("\" disabled></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label for=\"quantityInput\">Enter Quantity</label></td>\r\n");
      out.write("                    <td><input type=\"number\" id=\"quantityInput\" placeholder=\"Enter the Quantity..\" name=\"Quantity\" oninput=\"calculateSum()\" required></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><label for=\"productDiscount\">Discount (%)</label></td>\r\n");
      out.write("                    <td><input type=\"number\" id=\"productDiscount\" value=\"");
      out.print( currentProduct.getDiscount() );
      out.write("\" disabled></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("            <!-- Calculation Output -->\r\n");
      out.write("            <div class=\"calc-output\">\r\n");
      out.write("                <h2>Payment Calculation</h2>\r\n");
      out.write("                <input type=\"text\" id=\"purchaseQuantity\" disabled><br>\r\n");
      out.write("                <input type=\"text\" id=\"unitCost\" disabled><br>\r\n");
      out.write("                <input type=\"text\" id=\"discount\" disabled><br>\r\n");
      out.write("                <input type=\"text\" id=\"totalCost\" disabled><br>\r\n");
      out.write("                <input type=\"text\" id=\"discountDeduction\" disabled><br>\r\n");
      out.write("                <input type=\"text\" id=\"totalDiscount\" disabled><br>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Confirm Purchase Button -->\r\n");
      out.write("            <button class=\"confirm-button\" type=\"button\" onclick=\"showPaymentMethods()\">Confirm Purchase</button>\r\n");
      out.write("\r\n");
      out.write("            <!-- Payment Options Section -->\r\n");
      out.write("            <div id=\"paymentMethods\">\r\n");
      out.write("                <form action=\"OrderAndPayment\">\r\n");
      out.write("                    <input value=\"");
      out.print( customer.getId() );
      out.write("\" hidden=\"true\" name=\"customerID\">\r\n");
      out.write("                    <input value=\"");
      out.print( currentProduct.getId() );
      out.write("\" hidden=\"true\" name=\"productID\">\r\n");
      out.write("                    <input id=\"sendQuantity\" hidden=\"true\" name=\"purchaseQuantity\">\r\n");
      out.write("                    <input id=\"sendtotalCost\" hidden=\"true\" name=\"totalCost\">\r\n");
      out.write("                    <input id=\"stockAvailable\" value=\"");
      out.print( currentProduct.getQuantity() );
      out.write("\" hidden=\"true\" name=\"currentQuantity\">\r\n");
      out.write("                    <label for=\"paymentMethod\">Choose Payment Method:</label><br>\r\n");
      out.write("                    <div class=\"payment-options\">\r\n");
      out.write("                        <input type=\"radio\" id=\"upi\" name=\"paymentMethod\" value=\"UPI\">\r\n");
      out.write("                        <label for=\"upi\">UPI</label>\r\n");
      out.write("                        <input type=\"radio\" id=\"debit\" name=\"paymentMethod\" value=\"Debit\">\r\n");
      out.write("                        <label for=\"debit\">Debit Card</label>\r\n");
      out.write("                        <input type=\"radio\" id=\"credit\" name=\"paymentMethod\" value=\"Credit\">\r\n");
      out.write("                        <label for=\"credit\">Credit Card</label>\r\n");
      out.write("                        <input type=\"radio\" id=\"emi\" name=\"paymentMethod\" value=\"EMI\">\r\n");
      out.write("                        <label for=\"emi\">EMI</label>\r\n");
      out.write("                        <input type=\"radio\" id=\"netbanking\" name=\"paymentMethod\" value=\"Net Banking\">\r\n");
      out.write("                        <label for=\"netbanking\">Net Banking</label>\r\n");
      out.write("                        <input type=\"radio\" id=\"cod\" name=\"paymentMethod\" value=\"Cash On Delivary\">\r\n");
      out.write("                        <label for=\"cod\">COD</label>\r\n");
      out.write("                        <input type=\"radio\" id=\"wallet\" name=\"paymentMethod\" value=\"Wallet\">\r\n");
      out.write("                        <label for=\"wallet\">Wallet</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"submit\" class=\"submit-button\" value=\"Proceed to Payment\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
