/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2025-02-09 07:04:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import com.eshoping.modeal.Order_Details;
import com.eshoping.DAO.OrdersDAOimpl;
import com.eshoping.DAO.OrdersDAO;
import com.eshoping.modeal.Customer_Details;

public final class CustomerOrders_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.eshoping.DAO.OrdersDAO");
    _jspx_imports_classes.add("com.eshoping.modeal.Order_Details");
    _jspx_imports_classes.add("com.eshoping.DAO.OrdersDAOimpl");
    _jspx_imports_classes.add("com.eshoping.modeal.Customer_Details");
    _jspx_imports_classes.add("java.util.stream.Collectors");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Customer Orders</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/FooterStyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    /* Table styles */\r\n");
      out.write("    .order-table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .order-table th, .order-table td {\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Header style */\r\n");
      out.write("    .order-table th {\r\n");
      out.write("        background-color: #4CAF50;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Row styling on hover */\r\n");
      out.write("    .order-table tr:nth-child(even) {\r\n");
      out.write("        background-color: #f2f2f2;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .order-table tr:hover {\r\n");
      out.write("        background-color: #ddd;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    img {\r\n");
      out.write("        width: 50px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
 
        // Java Code: Getting customer details and orders
        Customer_Details customer_Details = (Customer_Details) session.getAttribute("loginincludecustomerdetail");
        OrdersDAO ordersDAO = new OrdersDAOimpl();
        List<Order_Details> orders = ordersDAO.getAllOrders();

        // Filter orders for the specific customer
        List<Order_Details> customerProduct = orders.stream()
            .filter(order -> order.getCustomer_Id() == customer_Details.getId())
            .collect(Collectors.toList());

     // Define a custom order for the statuses
        List<String> statusOrder = Arrays.asList(
            "Order Packed",
            "Dispatched from Hub",
            "Reached to Near Hub",
            "Out For Delivery",
            "Delivered",
            "Cancelled"
        );

        // Sort orders by the defined custom status order
        customerProduct.sort((o1, o2) -> {
            int statusIndex1 = statusOrder.indexOf(o1.getStatus());
            int statusIndex2 = statusOrder.indexOf(o2.getStatus());
            return Integer.compare(statusIndex1, statusIndex2); // Compare by status index
        });
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1>Customer Orders</h1>\r\n");
      out.write("        <h1>");
      out.print( "Name: " + customer_Details.getName() );
      out.write("</h1>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Single table to display all orders -->\r\n");
      out.write("        <table class=\"order-table\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>Order ID</th>\r\n");
      out.write("                    <th>Image</th>\r\n");
      out.write("                    <th>Cost</th>\r\n");
      out.write("                    <th>Date</th>\r\n");
      out.write("                    <th>Time</th>\r\n");
      out.write("                    <th>Quantity</th>\r\n");
      out.write("                    <th>Status</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                ");
 
                    // Loop through all customer orders and display them in the table
                    for (Order_Details order : customerProduct) { 
                
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print( order.getOrder_id() );
      out.write("</td>\r\n");
      out.write("                        <td><img src=\"images/");
      out.print( order.getImg() );
      out.write("\" alt=\"Product Image\"></td>\r\n");
      out.write("                        <td>");
      out.print( order.getTotal_Purchase_Prise() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( order.getPurchase_Date() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( order.getPurchase_Time() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( order.getPurchase_Quantity() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( order.getStatus() );
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                ");
 
                    } 
                
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
