/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2025-02-09 07:06:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.stream.Collectors;
import com.eshoping.modeal.Order_Details;
import java.util.List;
import com.eshoping.DAO.OrdersDAOimpl;
import com.eshoping.DAO.OrdersDAO;

public final class GetOrderDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.eshoping.DAO.OrdersDAO");
    _jspx_imports_classes.add("com.eshoping.modeal.Order_Details");
    _jspx_imports_classes.add("com.eshoping.DAO.OrdersDAOimpl");
    _jspx_imports_classes.add("java.util.stream.Collectors");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Customer Orders</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&family=Open+Sans:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("/* General container styles */\r\n");
      out.write(".container {\r\n");
      out.write("    width: 85%;\r\n");
      out.write("    margin: 20px auto;\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Title styling */\r\n");
      out.write("h1 {\r\n");
      out.write("    font-family: 'Open Sans', sans-serif;\r\n");
      out.write("    font-size: 28px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Grid container for the order display */\r\n");
      out.write(".order-wrapper {\r\n");
      out.write("    display: grid;\r\n");
      out.write("    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));\r\n");
      out.write("    gap: 20px;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Individual order card styling */\r\n");
      out.write(".order-card {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".order-card:hover {\r\n");
      out.write("    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    transform: translateY(-5px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".order-card img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-height: 150px;\r\n");
      out.write("    object-fit: contain;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Order card details styling */\r\n");
      out.write(".order-card div {\r\n");
      out.write("    font-family: 'Roboto', sans-serif;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin: 5px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".order-card .details {\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Button styling for \"Update Status\" */\r\n");
      out.write("button {\r\n");
      out.write("    padding: 8px 20px;\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("    align-self: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Styling for empty orders message */\r\n");
      out.write(".no-orders-message {\r\n");
      out.write("    color: #e74c3c;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Media query for mobile responsiveness */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    .order-wrapper {\r\n");
      out.write("        grid-template-columns: 1fr;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 
// Get all orders from the DAO
OrdersDAO ordersDAO = new OrdersDAOimpl();
List<Order_Details> totalOrders = ordersDAO.getAllOrders();

// Default filter is for Delivered Orders
String filterStatus = request.getParameter("filterStatus");
if (filterStatus == null) {
    filterStatus = "Delivered"; // Default filter to Delivered
}

// Make filterStatus effectively final by not reassigning it after initial declaration
final String finalFilterStatus = filterStatus; // Declare a final variable

// Filter the orders based on selected status
List<Order_Details> orders = totalOrders.stream()
    .filter(order -> {
        String status = order.getStatus();
        // Treat "Delivered" and "Cancelled" as their respective statuses
        if ("Delivered".equals(status)) {
            return finalFilterStatus.equals("Delivered");
        } else if ("Cancelled".equals(status)) {
            return finalFilterStatus.equals("Cancelled");
        } else {
            // Treat all other statuses as "Pending"
            return finalFilterStatus.equals("Pending");
        }
    })
    .collect(Collectors.toList());

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h1>Customer Orders</h1>\r\n");
      out.write("\r\n");
      out.write("    <!-- Dropdown for selecting order status -->\r\n");
      out.write("    <form method=\"get\">\r\n");
      out.write("        <label for=\"filterStatus\">Filter Orders by Status:</label>\r\n");
      out.write("        <select name=\"filterStatus\" id=\"filterStatus\">\r\n");
      out.write("            <option value=\"Pending\" ");
      out.print( "Pending".equals(finalFilterStatus) ? "selected" : "" );
      out.write(">Pending Orders</option>\r\n");
      out.write("            <option value=\"Cancelled\" ");
      out.print( "Cancelled".equals(finalFilterStatus) ? "selected" : "" );
      out.write(">Cancelled Orders</option>\r\n");
      out.write("            <option value=\"Delivered\" ");
      out.print( "Delivered".equals(finalFilterStatus) ? "selected" : "" );
      out.write(">Delivered Orders</option> <!-- Added Delivered option -->\r\n");
      out.write("        </select>\r\n");
      out.write("        <button type=\"submit\">Apply Filter</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <!-- Order wrapper for all rows -->\r\n");
      out.write("    <div class=\"order-wrapper\">\r\n");
      out.write("        ");
 if (orders.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"no-orders-message\">\r\n");
      out.write("                No Orders Available\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <!-- Loop through each order and display it in a card format -->\r\n");
      out.write("            ");
 for (Order_Details order : orders) { 
      out.write("\r\n");
      out.write("                <div class=\"order-card\">\r\n");
      out.write("                    <!-- Order Image -->\r\n");
      out.write("                    <img alt=\"notFound\" src=\"images/");
      out.print( order.getImg() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Order Details -->\r\n");
      out.write("                    <div>Order ID: ");
      out.print( order.getOrder_id() );
      out.write("</div>\r\n");
      out.write("                    <div>Customer ID: ");
      out.print( order.getCustomer_Id() );
      out.write("</div>\r\n");
      out.write("                    <div>Product ID: ");
      out.print( order.getProduct_Id() );
      out.write("</div>\r\n");
      out.write("                    <div>Payment ID: ");
      out.print( order.getPayment_Id() );
      out.write("</div>\r\n");
      out.write("                    <div>Quantity: ");
      out.print( order.getPurchase_Quantity() );
      out.write("</div>\r\n");
      out.write("                    <div>Purchase Date: ");
      out.print( order.getPurchase_Date() );
      out.write("</div>\r\n");
      out.write("                    <div>Purchase Time: ");
      out.print( order.getPurchase_Time() );
      out.write("</div>\r\n");
      out.write("                    <div>Total Price: ");
      out.print( order.getTotal_Purchase_Prise() );
      out.write("</div>\r\n");
      out.write("                    <div>Status: ");
      out.print( order.getStatus() );
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Conditionally render \"Update Status\" Button only for Pending orders -->\r\n");
      out.write("                    ");
 if (!"Delivered".equals(order.getStatus()) && !"Cancelled".equals(order.getStatus())) { 
      out.write("\r\n");
      out.write("                        <form action=\"ProductStatusUpdate.jsp\">\r\n");
      out.write("                            <input type=\"hidden\" value=\"");
      out.print( order.getOrder_id() );
      out.write("\" name=\"orderId\">\r\n");
      out.write("                            <button type=\"submit\">Update Status</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
