/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2025-02-09 07:06:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.eshoping.modeal.Order_Details;
import com.eshoping.DAO.OrdersDAOimpl;
import com.eshoping.DAO.OrdersDAO;

public final class ProductStatusUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.eshoping.DAO.OrdersDAO");
    _jspx_imports_classes.add("com.eshoping.modeal.Order_Details");
    _jspx_imports_classes.add("com.eshoping.DAO.OrdersDAOimpl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Update Order Status</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&family=Open+Sans:wght@400;600&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("/* General container styles */\r\n");
      out.write(".container {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	margin: 50px auto;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Title styling */\r\n");
      out.write("h1 {\r\n");
      out.write("	font-family: 'Open Sans', sans-serif;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Order card container */\r\n");
      out.write(".order-card {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	background-color: #f9f9f9;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".order-card img {\r\n");
      out.write("	max-width: 200px;\r\n");
      out.write("	max-height: 200px;\r\n");
      out.write("	object-fit: contain;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Details Section */\r\n");
      out.write(".order-details {\r\n");
      out.write("	font-family: 'Roboto', sans-serif;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Dropdown style */\r\n");
      out.write(".select-status {\r\n");
      out.write("	font-family: 'Roboto', sans-serif;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Submit Button */\r\n");
      out.write(".update-status-btn {\r\n");
      out.write("	padding: 12px 30px;\r\n");
      out.write("	background-color: #007bff;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".update-status-btn:hover {\r\n");
      out.write("	background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Error or Success messages */\r\n");
      out.write(".message {\r\n");
      out.write("	color: green;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error-message {\r\n");
      out.write("	color: red;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("    // JavaScript function for confirming delete action\r\n");
      out.write("    function confirmDelete() {\r\n");
      out.write("        var userConfirmed = confirm(\"Are you sure you want to Cancel this order?\");\r\n");
      out.write("        return userConfirmed; // If the user clicks \"OK\", it returns true, which will allow the form submission.\r\n");
      out.write("        // If the user clicks \"Cancel\", it returns false, preventing the form submission.\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
 int ordId=Integer.parseInt(request.getParameter("orderId"));
		OrdersDAO dao=new OrdersDAOimpl();
		Order_Details currentOrder=null;
		List<Order_Details> orders= dao.getAllOrders();
		for(Order_Details order:orders)
		{
			if(ordId==order.getOrder_id())
				currentOrder=order;
		}

      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("		<h1>Update Order Status</h1>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"order-card\">\r\n");
      out.write("			<!-- Order Image -->\r\n");
      out.write("			<img src=\"images/");
      out.print( currentOrder.getImg() );
      out.write("\" alt=\"Order Image\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Order Details -->\r\n");
      out.write("			<div class=\"order-details\">\r\n");
      out.write("				<strong>Order ID:</strong>\r\n");
      out.write("				");
      out.print( currentOrder.getOrder_id() );
      out.write("<br> <strong>Customer\r\n");
      out.write("					ID:</strong>\r\n");
      out.write("				");
      out.print( currentOrder.getCustomer_Id() );
      out.write("<br> <strong>Product\r\n");
      out.write("					ID:</strong>\r\n");
      out.write("				");
      out.print( currentOrder.getProduct_Id() );
      out.write("<br> <strong>Payment\r\n");
      out.write("					ID:</strong>\r\n");
      out.write("				");
      out.print( currentOrder.getPayment_Id() );
      out.write("<br> <strong>Quantity:</strong>\r\n");
      out.write("				");
      out.print( currentOrder.getPurchase_Quantity() );
      out.write("<br> <strong>Purchase\r\n");
      out.write("					Date:</strong>\r\n");
      out.write("				");
      out.print( currentOrder.getPurchase_Date() );
      out.write("<br> <strong>Purchase\r\n");
      out.write("					Time:</strong>\r\n");
      out.write("				");
      out.print( currentOrder.getPurchase_Time() );
      out.write("<br> <strong>Total\r\n");
      out.write("					Price:</strong>\r\n");
      out.write("				");
      out.print( currentOrder.getTotal_Purchase_Prise() );
      out.write("<br> <strong>Status:</strong>\r\n");
      out.write("				");
      out.print( currentOrder.getStatus() );
      out.write("<br>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Status Update Dropdown -->\r\n");
      out.write("			<form action=\"updateOrders\">\r\n");
      out.write("				<input type=\"hidden\" name=\"orderId\" value=\"");
      out.print( currentOrder.getOrder_id() );
      out.write("\"> \r\n");
      out.write("				<select\r\n");
      out.write("					name=\"status\" class=\"select-status\">\r\n");
      out.write("					<option value=\"\" disabled selected>Select Order Status</option>\r\n");
      out.write("					<option value=\"Order Packed\">Order Packed</option>\r\n");
      out.write("					<option value=\"Dispatched From Hub\">Dispatched from Hub</option>\r\n");
      out.write("					<option value=\"Reached To NearHub\">Reached to Near Hub</option>\r\n");
      out.write("					<option value=\"Out For Delivery\">Out For Delivery</option>\r\n");
      out.write("					<option value=\"Delivered\">Delivered</option>\r\n");
      out.write("				</select>\r\n");
      out.write("\r\n");
      out.write("				<!-- Submit Button -->\r\n");
      out.write("				<button type=\"submit\" class=\"update-status-btn\">Update Status</button>\r\n");
      out.write("			</form>\r\n");
      out.write("			<form action=\"cancelOrder\" onsubmit=\"return confirmDelete()\">\r\n");
      out.write("				<input type=\"hidden\" name=\"orderId\" value=\"");
      out.print( currentOrder.getOrder_id() );
      out.write("\"> \r\n");
      out.write("				<input type=\"hidden\" name=\"status\" value=\"Cancelled\"> \r\n");
      out.write("				<button type=\"submit\" class=\"update-status-btn\">Cancel</button>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
